### ISSUE TITLE
Crash after spotify connect

### ISSUE THREAD

**Issue by mezotv** [jaxcksn/nanoleafMusic#17] opened 2021-10-10 09:28 UTC
After i connect spotify i get an error message(that closes instand) and the software crashes making it unusabke

**Comment by jaxcksn** [comment] 2021-10-10 17:04
Would you mind posting a screenshot of the error message? I'm in college and don't have access to my light panels so it's unlikely that I'll be able to fix it anytime soon.

**Comment by mezotv** [comment] 2021-10-10 19:11
> You would mind posting a screenshot of the error message? I'm in college and don't have access to my light panels so it's unlikely that I'll be able to fix it anytime soon.

I would do that but the message closes instant

**Comment by alexoconnell** [comment] 2021-10-21 21:38
I just tried this app and get the same issue, connect to spotify and then it closes. No error that I see.

**Comment by inthenick** [comment] 2021-10-22 20:06
I have the same issue on MacOS Big Sur 11.6.

**Comment by jaxcksn** [comment] 2021-10-24 16:51
Like I said, I'm in college at the moment, so I probably won't get the chance to fix this until around December. I apologize that it's broken right now, from the looks of it, it seems like it's an issue with the spotify authentication.

**Comment by mezotv** [comment] 2021-12-21 22:32
Any updates on that ?

**Comment by LadeShootH** [comment] 2021-12-28 00:37
i have the same problem and i found the log file, so maybe this will help

these are the last few lines


01:25:21 [effect-start] INFO nanoleafMusic.EffectManager - Effect timer was scheduled
01:25:21 [effect-start] INFO nanoleafMusic.EffectManager - Spotify Poll timer was scheduled
01:25:21 [Thread-10] WARN nanoleafMusic.MusicEffect - Unrecoverable exception was thrown. Shutting down program.
01:25:21 [Thread-10] ERROR nanoleafMusic.Main - An Exception was Thrown
io.github.rowak.nanoleafapi.StatusCodeException$BadRequestException: 400 Bad Request.
	at io.github.rowak.nanoleafapi.Aurora.checkStatusCode(Aurora.java:1699)
	at io.github.rowak.nanoleafapi.Aurora.access$300(Aurora.java:29)
	at io.github.rowak.nanoleafapi.Aurora$Effects.writeEffect(Aurora.java:994)
	at io.github.rowak.nanoleafapi.Aurora$Effects.displayEffect(Aurora.java:785)
	at dev.jaxcksn.nanoleafMusic.effects.PulseBeatEffect.lambda$run$0(PulseBeatEffect.java:157)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by jaxcksn** [comment] 2021-12-28 07:16
Thank you for the information, from the looks of it, the problem is with the Aurora API, I'll have to see if they updated the endpoints. I can't give an estimate on when this will be fixed, but I will work on it as soon as I get the chance.  I'm planning on remaking this program in a different language anyways from scratch, so I might do that instead of trying to fix these issues.

**Comment by Ry-DS** [comment] 2022-05-05 14:22
Solved in #21 using the new Nanoleaf API. Haven't provided a build but if you build it yourself, works great with the new Nanoleaf devices.

**Closed as completed** 2022-05-16 15:33 UTC
Labels: bug
